# Change these first
owner: ak1ra-lab # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Homepage
    url: https://ak1ra.xyz
  - name: Images
    url: https://i.ak1ra.xyz
    expectedStatusCodes:
      - 404
  - name: GitHub Proxy
    url: https://gh.ak1ra.xyz
  - name: Wikipedia Proxy
    url: https://wikipedia.ak1ra.xyz/www/
  - name: Downloads
    url: https://dl.ak1ra.xyz
  - name: Subconverter
    url: https://sub.ak1ra.xyz/version
  - name: Docker Registry
    url: $GH_DOCKER_REGISTRY

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ak1ra.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "ak1ra-lab system status"
  introMessage: |
    **What is this page?**<br>
    ak1ra-lab provides open and flexible to users via its global network. This is the system status for the ak1ra-lab service, both edge network and public services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - ak1ra-komj

commitMessages:
  commitAuthorName: "ak1ra-bot"
  commitAuthorEmail: "bot@ak1ra.xyz"

user-agent: ak1ra-lab/status

robotsText: "User-agent: * \n Disallow: /"

i18n:
  footer: © ak1ra-lab

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
